Fix private registry installation procedure
pivotal-cf/docs-tas-kubernetes pull request #46
Opened 2020-10-06 09:03 UTC by mhoshi-vm

Fix private registry installation procedure

#45

2020-10-06 16:52 UTC, julian-hj requested changes
Hi @mhoshi-vm thanks for the suggestions. This PR is a bit difficult to work with however, as we don't have any context about what the problems were that you hit when you tried to follow the original documentation.

In order to help us try to get this documentation right, can you describe the problems you had, and how this revised set of steps makes them better?

Thanks,
-Julian

2020-10-06 16:52 UTC, julian-hj commented on configuring-sys-image-registry.html.md.erb
> +        sed -i 's/image: registry.pivotal.io/image: 10.195.35.68/g' relocated_images.yml
Presumably the IP address here needs to be replaced with some variant of PRIVATE_REPOSITORY?

2020-10-06 16:52 UTC, julian-hj commented on configuring-sys-image-registry.html.md.erb
> +        sed -i 's/image: registry.pivotal.io/image: 10.195.35.68/g' relocated_images.yml
Again, we need something other than an IP address here

2020-10-07 00:30 UTC, mhoshi-vm commented on configuring-sys-image-registry.html.md.erb
> -    docker login registry.SYSTEM-DOMAIN/ORG-NAME/REPOSITORY \
This line is wrong, as we should be logging into the docker repository.

2020-10-07 00:30 UTC, mhoshi-vm commented on configuring-sys-image-registry.html.md.erb
> -    * Where `SYSTEM-DOMAIN` is the system domain, such as `example.com`, that you previously selected for your
Updated this to only PRIVATE_REPOSITORY

2020-10-07 00:32 UTC, mhoshi-vm commented on configuring-sys-image-registry.html.md.erb
> -                         -r registry.SYSTEM-DOMAIN/ORG-NAME/REPOSITORY \
There is no registry running on registry.SYSTEM-DOMAIN so this has been updated

2020-10-07 00:32 UTC, mhoshi-vm commented on configuring-sys-image-registry.html.md.erb
> -        * `REPOSITORY` is the private registry repository to log in to.
Updated comment

2020-10-07 00:32 UTC, mhoshi-vm commented on configuring-sys-image-registry.html.md.erb
> -                         -r registry.SYSTEM-DOMAIN/ORG-NAME/REPOSITORY \
Same as above

2020-10-07 00:33 UTC, mhoshi-vm commented on configuring-sys-image-registry.html.md.erb
> -        * Where `SYSTEM-DOMAIN` is the system domain, such as `example.com`, that you previously selected for your
Same as above

2020-10-07 00:33 UTC, mhoshi-vm commented on configuring-sys-image-registry.html.md.erb
> -### <a id='configure-for-private-registry'></a> Customize Your Configuration to Use Your Private System Registry
This section does not look accurate and did not work for me i will add the reasons

2020-10-07 00:36 UTC, mhoshi-vm commented on configuring-sys-image-registry.html.md.erb
> -1. Move the `config/image-overrides.yml` file to the `config-optional` directory.
During "kpack package" all images are renamed to "registry.pivotal.io". 
The reallocation file created during "kpack unpackage" is based on the assumption that images are all from "registry.pivotal.io". 
Without this image-overrides, we are unable to convert the images via kbld properly as it is needed to covert to registry.pivotal.io

2020-10-07 00:37 UTC, mhoshi-vm commented on configuring-sys-image-registry.html.md.erb
> -1. To point the system registry variables to the private registry,
Changing `configuration-values/values.yml` has no affect to the later procedure as it get's overwritten to what it has at "../configure-values/system-registry.yaml"

2020-10-07 00:38 UTC, mhoshi-vm commented on installing-tas-for-kubernetes.html.md.erb
> -    * If your client has the private registry CA certificates:
The kbld command does not connect to registry, so there is no meaning to add certificate ignore flags

2020-10-07 00:38 UTC, mhoshi-vm commented on installing-tas-for-kubernetes.html.md.erb
> -        ```
The original command does not work as exepcted, and i was only able to find work with the updated version

2020-10-07 00:40 UTC, mhoshi-vm commented
hi @julian-hj 
I added as much as context as possible, but as you see , it needs major rewrite.
There is too many that is not accurate in the procedure, at least has not work in my envs so far

2020-10-12 18:23 UTC, merged